config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :activities
  resources :discoveries, only: [:show, :index, :new, :create]
  get "loader_discovery", to: "discoveries#loader", as: :loader_discovery
  # get "random_discovery", to: "discoveries#random_discovery", as: :random_discovery
  get "maps_sandbox", to: "pages#maps_sandbox", as: :maps_sandbox
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_one_attached :photo
  has_many :discoveries, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discovery.rb
class Discovery < ApplicationRecord
  belongs_to :activity, optional: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.save
    redirect_to activity_path(@activity)
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to activity_path(@activity)
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_path, status: :see_other
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :description, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/discoveries_controller.rb
class DiscoveriesController < ApplicationController

  def loader
    @activity = Activity.all.sample
  end

  def new
    @discovery = Discovery.new
    @activity = Activity.find(params[:activity_id])
    @discovery.activity = @activity
  end

  def create
    # break;
    @discovery = Discovery.new(discovery_params)
    @discovery.save
    redirect_to discovery_path(@discovery)
  end

  def show
    @discovery = Discovery.find(params[:id])
    @activity = @discovery.activity
  end

  private

  def discovery_params
    params.require(:discovery).permit(:activity, :activity_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @nb_activities = Activity.count
  end

  def map_sandbox

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= simple_form_for(@activity) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/activities/edit.html.erb
<h1>Modifier une Activité</h1>

<%= render "form" %>

app/views/activities/index.html.erb
<%= link_to "< Accueil", root_path %>

<h1>Activités</h1>

<ul>
  <% @activities.each do |activity| %>
    <li>
      <%= link_to activity.name, activity_path(activity) %>
        <div class="d-flex flex-row gap-2">
          <%= link_to("Modifier", edit_activity_path(activity), class:"btn btn-primary px-3 py-2 rounded-3") %>
          <%= link_to activity_path(activity), data: {
            turbo_method: :delete,
            turbo_confirm: "Supprimer l'activité' ?"
          },
          class: "btn btn-danger px-3 py-2 rounded-3" do %>
            <i class="fa-solid fa-trash-can text-white"></i>
          <% end %>
        </div>
    </li>
  <% end %>
</ul>

<%= link_to "Créer", new_activity_path, class: "btn btn-primary rounded-pill" %>

app/views/activities/new.html.erb
<h1>Créer une Activité</h1>

<%= render "form" %>

app/views/activities/show.html.erb
<%= link_to "< Toutes les activités", activities_path %>

<h1><%= @activity.name %></h1>

<p><%= @activity.description %></p>

<% if @activity.photo.attached? %>
  <%= cl_image_tag @activity.photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

<%= link_to("Modifier", edit_activity_path(@activity), class:"btn btn-primary px-3 py-2 rounded-3") %>

app/views/discoveries/_form.html.erb
<%# <%= form_with url: "restaurants", method: :post, local: true do |f| %>
<%= simple_form_for(@discovery) url: "restaurants", method: :post, local: true do |f| %>
  <%= f.hidden_field :activity %>
  <%= f.submit %>
<% end %>

app/views/discoveries/loader.html.erb
<div class="loader" data-controller="loader">
  <h1 data-loader-target="title">Ton activité arrive dans quelques secondes...</h1>
  <%= image_tag "svg/rolling_loader.svg", class: "loader-pending-img",
  :data => { "loader-target" => "pendingImg" } %>
  <p class="loader-success-img", data-loader-target="successImg">🥳</p>
  <div class="loader-action container", data-loader-target="successAction">
    <%= link_to "Découvrir l'activité",
    new_discovery_path(activity_id: @activity.id),
    class: "loader-success-btn btn btn-primary rounded-pill" %>
  </div>
</div>

app/views/discoveries/new.html.erb
<%= render "shared/activity_details" %>

<div class="block-action container">
  <%= simple_form_for(@discovery) do |f| %>
    <%= f.hidden_field :activity_id, value: @discovery.activity.id %>
    <%= f.submit value: "Cest parti !", class: "btn btn-primary rounded-pill" %>
  <% end %>

  <%= link_to "Relancer", loader_discovery_path, class: "btn btn-secondary rounded-pill" %>
</div>

<%# <%= link_to "Valider", {:controller => "discovery", :action => "create", :activity => @discovery.activity.id, method: :post } %>

<%# <%= render "form" %>

app/views/discoveries/show.html.erb
<div class="discovery-show-container">
  <h1>Tu as choisi le <span><%= @activity.name %></span>, c'est un super choix !</h1>

  <div class="msg-info">
    <p>Paprévu ne gère pas encore les réservations, nous t’invitons donc à consulter
      les horaires d’ouverture et à réserver cette activité par toi-même 😊</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paprevu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS_API_KEY"] %>"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>

app/views/pages/maps_sandbox.html.erb
<h1>Maps Sandbox</h1>

<h2>Display a map</h2>
<div data-controller="google-maps">
  <div id="map" style="width:100%;height:calc(70vh);;" data-google-maps-target="myMap"></div>
</div>

<h2>Enter an address</h2>
<p>TODO</p>

<h2>Get place details</h2>
<p>TODO</p>

app/views/shared/_activity_details.html.erb
<div class="activity-details-container">
  <div class="activity-banner">
    <% if @activity.photo.attached? %>
      <%= cl_image_tag @activity.photo.key, crop: :fill %>
    <% end %>
    <h1><%= @activity.name %></h1>
  </div>
  <div class="activity-body">
    <div class="activity-description">
      <h2>Description</h2>
      <p><%= @activity.description %></p>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-baseline">
    <h1>Trouve l'inattendu avec Paprévu !</h1>
    <h2>
      Un nouveau concept, une soirée délirante, des gens sympas...
      qui sait ce que tu découvriras
    </h2>
  </div>
  <div class="banner-action container">
    <h3>
      <span>
        <%= @nb_activities %>
        <%= @nb_activities > 1 ? "activités" : "activité" %>

        </span>
      à Lille
    </h3>
    <%= link_to "Go !", loader_discovery_path, class: "btn btn-primary rounded-pill" %>
    <%# <%= link_to "Activités", activities_path, class: "btn btn-secondary rounded-pill" %>
    <%# <%= link_to "Map Sandbox", maps_sandbox_path, class: "btn btn-secondary rounded-pill" %>
  </div>
</div>